service: serverless-go
frameworkVersion: '>= 3.38.0'
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}

functions:
  api:
   memorySize: 3008
   timeout: 10
   handler: bin/main
   events:
     - http:
         path: /api
         method: GET
     - http:
         path: /api/notes
         method: GET
    
  

package:
  patterns:
   - "!*/**"
   - bin/main